<!DOCTYPE HTML>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>sbt - $title$</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="assets/bootstrap_style.min.css">
    <link rel="stylesheet" href="assets/bootstrap-theme.min.css">
    <link rel="stylesheet" href="assets/stylesheet.css?v2021-07-04">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel='shortcut icon' href="assets/favicon.ico" />
    <link rel="icon" type="image/png" sizes="32x32" href="assets/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="assets/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="assets/favicon-16x16.png">

    <!-- OneTrust Cookies Consent Notice (Production Standard, scala-sbt.org, en-GB) start -->
    <script src="https://optanon.blob.core.windows.net/consent/d759c5db-6821-46e0-a988-6bc699efb74e.js" type="text/javascript" charset="UTF-8"></script>
    <script type="text/javascript">
      function OptanonWrapper() {
        //callback when OneTrust is loaded and ready
      }
    </script>
    <!-- OneTrust Cookies Consent Notice (Production Standard, scala-sbt.org, en-GB) end -->

    <link rel="stylesheet"href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />
  </head>
  <body class="default">
    <header>
      <nav>
        <div class="container">
          <div class="row">
            <div class="col-md-2 col-xs-3">
              <div class="logo">
                <a href="/index.html">
                  <img src="assets/sbt-logo.svg" alt="sbt">
                </a>
              </div>
            </div>
            <div class="col-md-7 col-xs-9">
              <div class="nav" id="topbar">
                <a href="/learn.html">Learn</a>
                <a href="/download.html">Download</a>
                <a href="/community.html">Get Involved</a>
                <a id="source-code" href="https://github.com/sbt/sbt"><img src="assets/github-logo-teal.svg" alt="Source code" class="social"></a>
                <a id="twitter" href="https://twitter.com/scala_sbt"><img src="assets/twitter-logo-teal.svg" alt="sbt on Twitter" class="social"></a>
              </div>
            </div>
            <div class="col-md-3">
              <div class="docsearch">
                <input type="text" id="doc-search-bar" placeholder="Search...">
                <ul class="result-container" id="result-container" style="display: none;"></ul>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <div class="page-title">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1>$title$</h1>
          </div>
        </div>
      </div>
    </div>
    <div class="fw-wrapper white">
      <div class="container content">
        <div class="row">
          <div class="col-md-8">
            <div id="main">
              $page.content$
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="fw-wrapper navy-ltr support-strip">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="support-item">
              <div class="support-icon">
                <svg class="svg-icon svg-icon-chat" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 97.5 85.2" enable-background="new 0 0 97.5 85.2"><path stroke="#fff" stroke-width="4.282" stroke-linecap="round" stroke-miterlimit="10" d="M27 29.5h-16.3c-4.7 0-8.6 3.9-8.6 8.6v25.7c0 4.7 3.9 8.6 8.6 8.6h2.7c.8 0 1.5.7 1.5 1.5v7.8c0 1.3 1.6 2 2.5 1l9.5-9.5c.5-.5 1.2-.8 2-.8h20.2c4.7 0 8.6-3.9 8.6-8.6v-7.8" fill="none"/><path fill="#fff" d="M85 0h-40c-6.9 0-12.5 5.6-12.5 12.5v33.4c0 2.2 1.8 4.1 4.1 4.1h29.9c.7 0 1.3.3 1.8.7l10 10c1.6 1.6 4.3.5 4.3-1.8v-6.5c0-1.4 1.1-2.5 2.5-2.5 6.9 0 12.5-5.6 12.5-12.5v-25c-.1-6.8-5.8-12.4-12.6-12.4z"/></svg>
              </div>
              <div class="support-detail">
                <h2>Community Support</h2>
                <a href="https://stackoverflow.com/questions/tagged/sbt">StackOverflow</a>
              </div>
            </div>
            <div class="support-item">
              <div class="support-icon">
                <svg id="lightbend-icon-reverse" class="svg-icon svg-icon-lightbend-reverse" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 302 262"><title>lightbend-icon</title><g id="icon"><path d="M1,195v56a10,10,0,0,0,10,10H291a10,10,0,0,0,10-10V195a557.85,557.85,0,0,1-150,20A557.85,557.85,0,0,1,1,195Z" style="fill:#fff"/><path d="M291,1H11A10,10,0,0,0,1,11V176a539.94,539.94,0,0,0,150,21,539.94,539.94,0,0,0,150-21V11A10,10,0,0,0,291,1Z" style="fill:#fff"/></g></svg>
              </div>
              <div class="support-detail">
                <h2>Commercial Support</h2>
                <a href="https://www.lightbend.com/services/expert-support">Lightbend Subscription</a>
                <a href="https://www.lightbend.com/services/training">Training</a>
                <a href="https://www.lightbend.com/services/consulting">Consulting</a>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

    <footer>
      <div class="container footer">
        <div class="row">
          <div class="col-md-8 sbt">
            <nav>
              <a href="/index.html">
                <img src="assets/sbt-logo-reverse.svg" alt="sbt">
              </a>
              <a href="/learn.html">Learn</a>
              <a href="/download.html">Download</a>
              <a href="/community.html">Get Involved</a>
            </nav>
            <p class="legal">
              &copy; 2016-<script>document.write(new Date().getFullYear())</script> Lightbend, Inc. |
              <a href="https://www.lightbend.com/legal/licenses" target="_blank">Licenses</a> |
              <a href="https://www.lightbend.com/legal/terms" target="_blank">Terms</a> |
              <a href="https://www.lightbend.com/legal/privacy" target="_blank">Privacy Policy</a> |
              <a href="cookie.html">Cookie Listing</a> |
              <a class="optanon-toggle-display">Cookie Settings</a>
            </p>
          </div>
          <div class="col-md-4 text-right ts">
            <a href="https://www.lightbend.com">
              <img src="assets/lightbend_reverse.png" alt="Lightbend, Inc.">
            </a>

          </div>
        </div>
      </div>
    </footer>
    <!-- Placed at the end -->
    <script src="assets/jquery.min.js" type="text/javascript"></script>
    <script src="assets/bootstrap.min.js" type="text/javascript"></script>
    <script src="assets/arc.js"></script>
    <script type="text/plain" class="optanon-category-2" async>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-41449189-1', 'scala-sbt.org');
    ga('send', 'pageview');
    </script>
    <script type="text/plain" class="optanon-category-2" async>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-23127719-1', 'lightbend.com', {'allowLinker': true, 'name': 'tsTracker'});
      ga('tsTracker.require', 'linker');
      ga('tsTracker.linker:autoLink', ['lightbend.com','playframework.com','scala-lang.org','scaladays.org','spray.io','akka.io','scala-sbt.org']);
      ga('tsTracker.send', 'pageview');
    </script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
    <script type="text/javascript"> docsearch({
      apiKey: 'e47ee877a07ea1c48722f08430d54913',
      indexName: 'scala-sbt',
      inputSelector: '#doc-search-bar',
      debug: false // Set debug to true if you want to inspect the dropdown
    });
    </script>    
  </body>
</html>
